level: info
max_queue: 2048

sinks:
  - type: terminal
    colorize: true

  - type: file
    path: "rover_log"        # will generate rover_log_0.log, rover_log_1.log, ...
    rotation_bytes: 200000   # ~200 KB for demo

modules:
  /drive: warn
  /vision: info
  /nav: debug
